export const ROUTES = {
    LOGIN: '/login',
    USER: (id: string) => `/users/${id}`,
    HOME: '/home',
    BREATH: '/breath',
    BREATH_ACTIVITY: '/breath/breathActivity',
    ONBOARDING: '/onboarding',
    ONBOARDING_WEB: '/onboarding/web',
    PRIVACY_POLICY: '/privacy-policy',
    CHECKIN: '/checkin',
    FORGOT_PASSWORD: '/login/forgotPassword',
    PROFILE: '/profile',
    GAV: '/gav',
    FLORA: '(tabs)/flora',
    CALENDAR: '(tabs)/(checkin)/calendarCheckin',
    NOTIFICATIONS: '(tabs)/notification',
    ONBOARDING_FIRST_ACCESS: '/onboarding/StartJornada3',
    PLAN: '(tabs)/plan',
    PAYMENT: '/payment',
    CHECKOUT: '/payment/checkoutScreen',
    NOVO_USUARIO: '/onboarding/novo-usuario',
    SUPORT: '/suport',
    SUPORT_CHAT: '/suport/chat',
    MEU_PLANO: '(tabs)/plan/meuPlano',
    CANCELAR_ASSINATURA: '(tabs)/plan/cancelarAssinatura',
    HISTORICO_FATURAS: '(tabs)/plan/historicoFaturas',
} as const;